jwt_secret: un-secret-tres-long-et-securise
default_redirection_url: https://grist.macloud.fr
server:
  host: 0.0.0.0
  port: 9091
authentication_backend:
  file:
    path: /config/users_database.yml
access_control:
  default_policy: deny
  rules:
    - domain: "grist.macloud.fr"
      policy: two_factor  # Active la 2FA pour Grist (optionnel)
session:
  secret: un-autre-secret-tres-long
  domain: macloud.fr  # Domaine principal pour les cookies de session