identity_validation:
  reset_password:
    jwt_secret: un-secret-tres-long-et-securise

server:
  host: 0.0.0.0
  port: 9091

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: "grist.macloud.fr"
      policy: one_factor

session:
  secret: un-autre-secret-tres-long
  cookies:
    - name: authelia_session
      domain: macloud.fr
      authelia_url: https://auth.macloud.fr

storage:
  encryption_key: une-cle-de-chiffrement-longue-et-securisee
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notifications.txt