version: "3.9"

services:
  grist:
    image: gristlabs/grist:1.3.3
    container_name: grist
    expose:
      - "8484"
    volumes:
      - grist_data:/persist
    environment:
      - GRIST_SESSION_SECRET=un-secret-tres-long-et-securise
      - GRIST_DEFAULT_EMAIL=admin@macloud.fr
      - GRIST_DOMAIN=grist.macloud.fr
      - GRIST_FORCE_LOGIN=true
      - GRIST_SINGLE_ORG=macloud
      - GRIST_OIDC_ISSUER=https://dex.macloud.fr
      - GRIST_OIDC_LOGIN_TEXT=Connexion avec Authelia
      - GRIST_OIDC_LOGOUT_URL=https://auth.macloud.fr/logout
    restart: unless-stopped
    labels:
      - "dokploy.domain=grist.macloud.fr"
      - "dokploy.port=8484"

  authelia:
    image: authelia/authelia:4.38.5
    container_name: authelia
    expose:
      - "9091"
    volumes:
      - ./authelia_config/config.yml:/config/authelia.yml
      - ./authelia_config/users_database.yml:/config/users_database.yml
    environment:
      - AUTHELIA_JWT_SECRET=un-secret-tres-long-et-securise
      - AUTHELIA_SESSION_SECRET=un-autre-secret-tres-long
    restart: unless-stopped
    labels:
      - "dokploy.domain=auth.macloud.fr"
      - "dokploy.port=9091"

  dex:
    image: dexidp/dex:master
    container_name: dex
    expose:
      - "5556"
    volumes:
      - ./dex_config/dex.yaml:/etc/dex/config.yaml
      - dex_data:/var/lib/dex
    command: ["sh", "-c", "mkdir -p /var/lib/dex && chmod 777 /var/lib/dex && dex serve /etc/dex/config.yaml"]
    restart: unless-stopped
    labels:
      - "dokploy.domain=dex.macloud.fr"
      - "dokploy.port=5556"

volumes:
  grist_data:
  dex_data: