version: "3.9"
services:
  grist-omnibus:
    image: gristlabs/grist-omnibus:latest
    container_name: grist_omnibus
    expose:
      - "80"
      - "443"
    volumes:
      - grist_data:/persist
      - ./dex.yaml:/custom/dex.yaml
    environment:
      - EMAIL=admin@macloud.fr
      - DOMAIN=grist.macloud.fr
      - URL=https://grist.macloud.fr
      - HTTPS=auto
      - TEAM=macloud
    depends_on:
      - ldap
    restart: unless-stopped
    labels:
      - "dokploy.domain=grist.macloud.fr"
      - "dokploy.port=443"

  ldap:
    image: osixia/openldap:latest
    container_name: ldap_server
    expose:
      - "389"  # On expose uniquement LDAP, pas LDAPS
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./ldap-init.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/01-init.ldif
    environment:
      - LDAP_ORGANISATION=Macloud
      - LDAP_DOMAIN=macloud.fr
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_CONFIG_PASSWORD=secret
      - LDAP_BASE_DN=dc=macloud,dc=fr
      - LDAP_TLS=false  # Désactive TLS explicitement
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ldapsearch", "-x", "-H", "ldap://localhost:389", "-D", "cn=admin,dc=macloud,dc=fr", "-w", "secret", "-b", "dc=macloud,dc=fr", "-s", "base"]
      interval: 10s
      timeout: 5s
      retries: 5

  ldap-admin:
    image: ldapaccountmanager/lam:latest
    container_name: ldap_admin
    expose:
      - "80"
    volumes:
      - lam_config:/var/www/html/config
    environment:
      - LAM_SKIP_PRECONFIGURE=true
    depends_on:
      - ldap
    restart: unless-stopped
    labels:
      - "dokploy.domain=ldap-admin.macloud.fr"
      - "dokploy.port=80"

volumes:
  grist_data:
  ldap_data:
  ldap_config:
  lam_config:
