version: "3.9"

services:
  grist:
    image: gristlabs/grist:latest
    container_name: grist
    expose:
      - "8484"
    volumes:
      - grist_data:/persist
    environment:
      - GRIST_SESSION_SECRET=un-secret-tres-long-et-securise
      - GRIST_DEFAULT_EMAIL=admin@macloud.fr
      - GRIST_DOMAIN=grist.macloud.fr
      - GRIST_FORCE_LOGIN=true
      - GRIST_SINGLE_ORG=macloud
      - GRIST_OIDC_ISSUER=https://dex.macloud.fr
      - GRIST_OIDC_LOGIN_TEXT=Connexion avec Authelia
      - GRIST_OIDC_LOGOUT_URL=https://auth.macloud.fr/logout
    restart: unless-stopped
    labels:
      - "dokploy.domain=grist.macloud.fr"
      - "dokploy.port=8484"

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    expose:
      - "9091"
    volumes:
      - ./authelia_config/config.yml:/config/configuration.yml
      - ./authelia_config/users_database.yml:/config/users_database.yml
    environment:
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET=un-secret-tres-long-et-securise
      - AUTHELIA_SESSION_SECRET=un-autre-secret-tres-long
    restart: unless-stopped
    labels:
      - "dokploy.domain=auth.macloud.fr"
      - "dokploy.port=9091"

  dex:
    image: dexidp/dex:latest
    container_name: dex
    expose:
      - "5556"
    volumes:
      - ./dex_config/dex.yaml:/etc/dex/config.yaml
    command: ["dex", "serve", "/etc/dex/config.yaml"]  # Forcer l’utilisation du fichier
    restart: unless-stopped
    labels:
      - "dokploy.domain=dex.macloud.fr"
      - "dokploy.port=5556"

volumes:
  grist_data: