version: "3.9"
services:
  grist-omnibus:
    image: gristlabs/grist-omnibus:latest
    container_name: grist_omnibus
    expose:
      - "80"  # Port HTTP interne uniquement
    volumes:
      - grist_data:/persist
      - ./dex.yaml:/custom/dex.yaml
    environment:
      - EMAIL=admin@macloud.fr
      - DOMAIN=grist.macloud.fr
      - URL=http://grist.macloud.fr  # URL interne en HTTP
      - HTTPS=manual  # Désactive Let's Encrypt dans Grist
      - TEAM=macloud-team
    depends_on:
      - ldap
    restart: unless-stopped
    labels:
      - "dokploy.domain=grist.macloud.fr"
      - "dokploy.port=80"  # Dokploy mappe HTTPS vers le port 80 interne

  ldap:
    image: bitnami/openldap:latest
    container_name: ldap_server
    expose:
      - "389"
    volumes:
      - ldap_data:/bitnami/openldap
      - ./ldap-init.ldif:/opt/bitnami/openldap/ldif/01-init.ldif
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_ROOT=dc=macloud,dc=fr
      - LDAP_SKIP_DEFAULT_TREE=yes
      - LDAP_CUSTOM_LDIF_DIR=/opt/bitnami/openldap/ldif
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ldapsearch", "-x", "-H", "ldap://localhost:389", "-D", "cn=admin,dc=macloud,dc=fr", "-w", "secret", "-b", "dc=macloud,dc=fr", "-s", "base"]
      interval: 10s
      timeout: 5s
      retries: 5

  ldap-admin:
    image: ldapaccountmanager/lam:latest
    container_name: ldap_admin
    expose:
      - "80"
    volumes:
      - lam_config:/var/www/html/config
    environment:
      - LAM_SKIP_PRECONFIGURE=true
    depends_on:
      - ldap
    restart: unless-stopped
    labels:
      - "dokploy.domain=ldap-admin.macloud.fr"
      - "dokploy.port=80"

volumes:
  grist_data:
  ldap_data:
  lam_config:
