version: "3.9"
services:
  grist-omnibus:
    image: gristlabs/grist-omnibus:latest
    container_name: grist_omnibus
    expose:
      - "80"    # Port HTTP interne au conteneur
      - "443"   # Port HTTPS interne au conteneur
    volumes:
      - grist_data:/persist
      - ./dex.yaml:/custom/dex.yaml  # Configuration Dex pour LDAP
    environment:
      - EMAIL=admin@macloud.fr
      - DOMAIN=grist.macloud.fr
      - URL=https://grist.macloud.fr  # URL publique explicite
      - HTTPS=auto  # HTTPS géré par Dokploy ou Traefik
      - TEAM=macloud  # Ajout de la variable TEAM
    depends_on:
      - ldap
    restart: unless-stopped
    labels:
      - "dokploy.domain=grist.macloud.fr"
      - "dokploy.port=443"  # Port principal du conteneur pour HTTPS

  ldap:
    image: osixia/openldap:latest
    container_name: ldap_server
    expose:
      - "389"  # Port LDAP interne
      - "636"  # Port LDAPS interne
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./ldap-init.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/01-init.ldif
    environment:
      - LDAP_ORGANISATION=Macloud
      - LDAP_DOMAIN=macloud.fr
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_CONFIG_PASSWORD=secret
      - LDAP_BASE_DN=dc=macloud,dc=fr
    restart: unless-stopped

  ldap-admin:
    image: ldapaccountmanager/lam:latest
    container_name: ldap_admin
    expose:
      - "80"  # Port interne pour l'interface web
    volumes:
      - lam_config:/var/www/html/config
    environment:
      - LAM_SKIP_PRECONFIGURE=true
    depends_on:
      - ldap
    restart: unless-stopped
    labels:
      - "dokploy.domain=ldap-admin.macloud.fr"  # Sous-domaine pour LAM
      - "dokploy.port=80"  # Port interne du conteneur

volumes:
  grist_data:
  ldap_data:
  ldap_config:
  lam_config:
